skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe" C:\Miniconda.exe
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - set PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda update --yes conda
  - conda install --yes conda-build
  - conda install --yes anaconda-client
  - conda-build .conda/libndtypes
  - conda-build .conda/ndtypes
  - ps: $LIBNDTYPES = (conda build --output .conda/libndtypes) | Out-String
  - ps: $NDTYPES = (conda build --output .conda/ndtypes) | Out-String

on_success:
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER (anaconda --token $env:anaconda_token upload "%LIBNDTYPES%" --user plures --channel main)
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER (anaconda --token $env:anaconda_token upload "%NDTYPES%" --user plures --channel main)

environment:
  anaconda_token:
    secure: rTnsCbMjHi/mOYo8Tz2SzaungqlrdypPkMMzuMniN06Gv2fgCizppeKw2gz/kQ7T
