sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_script:
        - python3 -m pip install numpy sphinx
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
      script:
        - ./configure --with-valgrind
        - make parser
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make parser
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
      script:
        - cd ndtypes
        - git fetch --unshallow
        - conda build .conda/libndtypes
        - conda build .conda/ndtypes
        - export LIBNDTYPES=`conda build --output .conda/libndtypes`
        - export NDTYPES=`conda build --output .conda/ndtypes`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBNDTYPES --user xnd --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $NDTYPES --user xnd --label dev; fi

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
      script:
        - cd ndtypes
        - git fetch --unshallow
        - conda build .conda/libndtypes
        - conda build .conda/ndtypes
