sudo: required
dist: trusty
python: 3.5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - valgrind

language: C

matrix:
  include:
    - compiler: gcc
      before_script:
        - export CC=gcc-4.9
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - export CC=gcc-4.9
      script:
        - ./configure --with-valgrind
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bison; brew link bison --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi


