skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON_ARCH: "x86_64"
      platform: x64
    - PYTHON_ARCH: "x86"
      platform: x86

before_build:
  "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %platform%"

build_script:
  - move /y Makefile.vc Makefile
  - nmake check


