package:
  name: ndtypes
  version: 0.2.0b2

requirements:
  build:
    - python >=3.6
    - bison  # [not win]
    - flex  # [not win]
    - m4  # [not win]
  run:
    - python >=3.6

about:
  home: https://github.com/plures/
  license: BSD
