package:
  name: ndtypes
  version: 0.2.0.b1

requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - python -m ndtypes.test.test_ndtypes

about:
  home: https://github.com/plures/
  license: BSD
